name: flutter_tagging
description: A flutter package with tagging or multiselect functionality. Useful for adding Tag or Label Selection Forms.
version: 3.0.2
repository: https://github.com/bradintheusa/flutter_tagging


environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_typeahead: 3.2.1
  collection: ">=1.14.11 <2.0.0"
  meta: ">=1.1.7 <2.0.0"

dev_dependencies:
  flutter_test:
    sdk: flutter
